<?php

namespace EmployeeBundle\Repository;

/**
 * AdminUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
