<?php

namespace EmployeeBundle\Repository;

/**
 * AssetTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
