<?php

namespace EmployeeBundle\Repository;

/**
 * ClaimedDeductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaimedDeductionRepository extends \Doctrine\ORM\EntityRepository
{
}
