<?php

namespace EmployeeBundle\Repository;

/**
 * DesignationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignationRepository extends \Doctrine\ORM\EntityRepository
{
}
