<?php

namespace EmployeeBundle\Repository;

/**
 * EmployeeAssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeAssetRepository extends \Doctrine\ORM\EntityRepository
{
}
