<?php

namespace EmployeeBundle\Repository;

/**
 * LeaveStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaveStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
