<?php

namespace EmployeeBundle\Repository;

/**
 * LeaveFaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaveFaqRepository extends \Doctrine\ORM\EntityRepository
{
}
