<?php

namespace EmployeeBundle\Repository;

/**
 * LeaveTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaveTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
