<?php

namespace EmployeeBundle\Repository;

/**
 * PaySlipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaySlipRepository extends \Doctrine\ORM\EntityRepository
{
}
