<?php

namespace EmployeeBundle\Repository;

/**
 * PfRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PfRateRepository extends \Doctrine\ORM\EntityRepository
{
}
