<?php

namespace EmployeeBundle\Repository;

/**
 * RequestTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
