<?php

namespace EmployeeBundle\Repository;

/**
 * ResetLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResetLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
