<?php

namespace EmployeeBundle\Repository;

/**
 * SalaryAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaryAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
