<?php

namespace EmployeeBundle\Repository;

/**
 * TaxSlabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxSlabRepository extends \Doctrine\ORM\EntityRepository
{
}
