<?php

namespace EmployeeBundle\Repository;

/**
 * TaxSlabSeniorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxSlabSeniorRepository extends \Doctrine\ORM\EntityRepository
{
}
