# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        EmployeeBundle\Entity\Employee:
            algorithm: bcrypt
        EmployeeBundle\Entity\AdminUsers:
            algorithm: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [db_provider, admin_db_provider]
        in_memory:
            memory: ~
        db_provider:
            entity:
                class: EmployeeBundle:Employee
                property: email
        admin_db_provider:
            entity:
                class: EmployeeBundle:AdminUsers
                property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            pattern: ^/auth
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: dashboard
            logout:
                path:   /auth/logout
                target: /auth/login 
                invalidate_session: true
        admin:
            anonymous: ~
            pattern: ^/admin
            provider: admin_db_provider
            form_login:
                login_path: adminLogin
                check_path: adminLogin
                default_target_path: admindashboard
            logout:
                path:   /admin/logout
                target: /admin/login
                invalidate_session: true
    access_control:
        - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth,roles: [ROLE_ADMIN, ROLE_EMPLOYEE]  }
        - { path: ^/admin, roles: ROLE_ADMIN }
